x = input('digite qualuer coisa:')
print('o tipo primitivo desse valor é', type(x))
print('é um numero?', x.isnumeric())
print('é alfabetico?', x.isalpha())
print('possui numeros e letras?', x.isalnum())
print('possui letras maiusculas?', x.isupper())
print('possui letras minusculas?', x.islower())
print('é somente espaços?', x.isspace())
print('esta capitalizado?', x.istitle())
